### ISSUE TITLE
build gradle

### ISSUE THREAD

**Issue by adamkeyser** [michaelgalvin/SENG5199-twtr#11]
I ended up adding  
`testCompile 'org.codehaus.groovy.modules.http-builder:http-builder:0.5.0-RC2'`

to the build, which seems to resolve the issue. I highly suggest bugging Mike about this. 

I pushed a branch up that you can take a look at if you wish. The build seems to work, some tests were failing. Hopefully this is helpful. 

The branch is `development_modified_gradle`

Take Care!

**Comment by michaelgalvin** [comment]
Yes!!!  it works now. Thanks Adam.  I updated the application.js and index.gsp with the Hello Stranger, and the test passes now.
