### ISSUE TITLE
Problems with loginRequirements branch

### ISSUE THREAD

**Issue by adamkeyser** [michaelgalvin/SENG5199-twtr#13]
Hey sorry, just got a second to look at this.

Where you define your routes you don't want to reference the templates directory, even though you're using it. I think it pushes all the html out of that directory into your app directory.

So in your angular-router.js file you want to change the following:
    templateUrl: '/app/templates/helloStranger.htm',    CHANGE TO ->>>>
    templateUrl: '/app/helloStranger.htm',

Once you get rid of the templates directory I think you'll be in good shape, let me know if you're not. Take care!

I'll update the readme's to reflect this, it's a rather confusing nuance!

**Comment by michaelgalvin** [comment]
That did it!  Thank you!
